name: calagem_brasil_pro
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ionicons: ^0.1.2
  material_design_icons_flutter: ^5.0.5955-rc.1
  range_calendar:
  awesome_dialog: ^2.1.1
  screenshot: ^1.2.3

  get: ^4.5.1
  get_storage: ^2.0.2
  intl: ^0.17.0
  cool_alert: ^1.1.0
  keyboard_utils: ^1.3.3
  carousel_slider: ^4.0.0
  pdf: ^3.4.2
  printing: ^5.4.3
  http: ^0.13.3
  sqflite: ^2.0.0+4
  path: ^1.8.0
  uuid: ^3.0.4
  dio: ^4.0.4
  fast_rsa: ^3.1.0
  dart_jsonwebtoken: ^2.4.0
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/


  fonts:
    - family: OpenSans
      fonts:
       - asset: assets/fonts/OpenSans-Regular.ttf
         weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: SpecialElite
      fonts:
        - asset: assets/fonts/SpecialElite-Regular.ttf
    - family: CourierRegular
      fonts:
        - asset: assets/fonts/CourierPrime-Regular.ttf
    - family: CourierBold
      fonts:
        - asset: assets/fonts/CourierPrime-Bold.ttf
